pipeline {
    agent any

    environment {
        // 指定 NodeJS 工具名稱和版本
        NODEJS_HOME = tool name: 'NodeJS-12', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        
        // 指定 npm 版本
        NPM_HOME = tool name: 'npm-6', type: 'jenkins.plugins.nodejs.tools.NpmPackagesInstallation'
        
        // 將 NodeJS 和 npm 加入 PATH
        PATH = "${env.NODEJS_HOME}/bin:${env.NPM_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                // Get source code from a GitHub repository
                git branch:'declandevops', url:'https://github.com/Tzu-Lun/GoExpertsFrontend.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir("./cicd/") {
                    sh 'npm install'
                }
            }
        }
        
        stage('Build') {
            steps {
                dir("./cicd/") {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Deploy to AWS S3 bucket') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'p3l1-jenkins-credential', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    dir("./cicd/") {
                      sh 'aws s3 ls'
                      sh 'aws s3 sync build s3://p3l1devops/'
                    }
                }
            }
        }
    }
}