pipeline {
    agent any

     environment {
        NODEJS_HOME = tool name: 'NodeJS', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        PATH = "${env.NODEJS_HOME}/bin:${env.PATH}"
    }

    tools {
        nodejs 'NodeJS-12' // 指定 Node.js 工具名
        npm 'npm-6' // 指定 npm 工具名
    }

    stages {
        stage('Checkout') {
            steps {
                // Get source code from a GitHub repository
                git branch:'declandevops', url:'https://github.com/Tzu-Lun/GoExpertsFrontend.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir("./cicd/") {
                    sh 'npm install'
                }
            }
        }
        stage('Update npm') {
    steps {
        sh 'npm install -g npm@7'  // 選擇一個與 Node.js v18 兼容的 npm 版本
    }
}

        stage('Build') {
            steps {
                dir("./cicd/") {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Deploy to AWS S3 bucket') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-p3l1-jenkins-credential', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    dir("./cicd/") {
                      sh 'aws s3 ls'
                      sh 'aws s3 sync build s3://p3l1devops/'
                    }
                }
            }
        }
    }
}